/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.sun.org.apache.xpath.internal.operations.Equals;
import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    public static class Contentor{
        int pos;

        public Contentor(int pos) {
            this.pos = pos;
        }
    }
    @Test
    public void GetSameInstance2Threads() throws InterruptedException{
        TransferQueue <Contentor> tq = new TransferQueue<>();
        Contentor msg = new Contentor(-1);
        Thread a = new Thread(() -> {
            try {
                tq.transfer(msg, 100000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });
        Contentor [] answer = new Contentor[1];
        Thread b = new Thread(() -> {
            try {

                tq.take(100000, answer);

            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });
        a.start();
        Thread.sleep(5000);
        b.start();


        a.join();
        b.join();

        Assert.assertEquals(msg, answer[0]);
    }
}
